file(GLOB_RECURSE UNIT_SOURCES CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/tests/*.cpp")
list(FILTER UNIT_SOURCES EXCLUDE REGEX "/tests/support/")
file(GLOB_RECURSE SUPPORT_SOURCES CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/tests/support/*.cpp")
add_library(MarmotcTestSupport STATIC ${SUPPORT_SOURCES})
target_include_directories(MarmotcTestSupport PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/tests)
target_link_libraries(MarmotcTestSupport PUBLIC MarmotDriver)
if(MSVC)
    target_compile_options(MarmotcTestSupport PRIVATE /EHsc)
endif()
get_filename_component(MARMOT_REPO_ROOT "${CMAKE_CURRENT_SOURCE_DIR}/../.." ABSOLUTE)
target_compile_definitions(MarmotcTestSupport PUBLIC MARMOT_REPO_ROOT="${MARMOT_REPO_ROOT}" MARMOT_PRELUDE_DIR="${MARMOT_REPO_ROOT}/MarmotPrelude")
add_executable(MarmotcUnitTests ${UNIT_SOURCES})
target_link_libraries(MarmotcUnitTests PRIVATE Catch2::Catch2WithMain MarmotDriver MarmotcTestSupport)
if(MSVC)
    target_compile_options(MarmotcUnitTests PRIVATE /EHsc)
endif()
include(${catch2_SOURCE_DIR}/extras/Catch.cmake)
catch_discover_tests(MarmotcUnitTests)

option(MIDORI_BUILD_INTEGRATION_TESTS "Build repository subprocess integration tests" OFF)
if(MIDORI_BUILD_INTEGRATION_TESTS)
    file(GLOB INTEGRATION_SOURCES CONFIGURE_DEPENDS "${MARMOT_REPO_ROOT}/test/integration/*.cpp")
    add_executable(MarmotIntegrationTests ${INTEGRATION_SOURCES})
    target_link_libraries(MarmotIntegrationTests PRIVATE Catch2::Catch2WithMain MarmotcTestSupport)
    add_library(marmot_test_native SHARED "${MARMOT_REPO_ROOT}/test/integration/native/TestNative.cpp")
    add_dependencies(MarmotIntegrationTests marmot_test_native)
    target_compile_definitions(MarmotIntegrationTests PRIVATE MARMOT_TEST_NATIVE_DIR="$<TARGET_FILE_DIR:marmot_test_native>")
    if(MSVC)
        target_compile_options(MarmotIntegrationTests PRIVATE /EHsc)
    endif()
endif()
