use super::{Plan, PlanNativeLibrary, make_plan};
use crate::paths;
use crate::test_support::{TempTree, compiler, package, project};
use std::path::{Path, PathBuf};

fn shown(path: &Path) -> String {
    paths::display(path)
}

fn plan_for(tree: &TempTree, entry: &str, environment: &[PathBuf]) -> Plan {
    make_plan(&tree.path(entry), environment, &compiler())
        .unwrap()
        .0
}

#[test]
fn without_a_manifest_the_search_paths_are_marmot_path() {
    let tree = TempTree::new(&[
        ("app/Main.mmt", "module Main\n"),
        ("lib/Lib.mmt", "module Lib\n"),
    ]);
    let environment = vec![
        tree.path("missing"),
        tree.path("lib"),
        tree.path("lib/../lib"),
    ];

    let plan = plan_for(&tree, "app/Main.mmt", &environment);

    assert_eq!(plan.entry, Some(shown(&tree.path("app/Main.mmt"))));
    assert_eq!(plan.search_paths, vec![shown(&tree.path("lib"))]);
    assert!(plan.native_libraries.is_empty());
}

#[test]
fn resolving_installs_packages_and_orders_the_search_paths() {
    let tree = TempTree::new(&[
        ("project.marmot", &project(&[("App", "^1.0.0")])),
        ("src/Main.mmt", "module Main\n"),
        (
            "registry/App/package.marmot",
            &package("App", "1.0.0", &[("Zeta", "^1.0.0"), ("Alpha", "^1.0.0")]),
        ),
        ("registry/App/App.mmt", "module App\n"),
        (
            "registry/Zeta/package.marmot",
            &package("Zeta", "1.0.0", &[]),
        ),
        (
            "registry/Alpha/package.marmot",
            &package("Alpha", "1.0.0", &[]),
        ),
        ("MarmotPrelude/IO.mmt", "module IO\n"),
        ("env/Env.mmt", "module Env\n"),
    ]);

    let plan = plan_for(&tree, "src/Main.mmt", &[tree.path("env"), tree.path("src")]);

    // App depends on Zeta and Alpha; with both ready, Alpha goes first.
    assert_eq!(
        plan.search_paths,
        vec![
            shown(&tree.path("src")),
            shown(&tree.path("packages/Alpha-1.0.0")),
            shown(&tree.path("packages/Zeta-1.0.0")),
            shown(&tree.path("packages/App-1.0.0")),
            shown(&tree.path("registry")),
            shown(&tree.path("MarmotPrelude")),
            shown(&tree.path("env")),
        ]
    );
    assert_eq!(tree.read("packages/App-1.0.0/App.mmt"), "module App\n");

    let lock = tree.read("marmot.lock");
    assert!(
        lock.starts_with("# Auto-generated by Marmot. Do not edit manually.\n[metadata]\n"),
        "{lock}"
    );
    assert!(
        lock.contains("source = \"local:packages/App-1.0.0\""),
        "{lock}"
    );
    assert!(
        lock.contains("dependencies = [\"Alpha@1.0.0\", \"Zeta@1.0.0\"]"),
        "{lock}"
    );
    let alpha = lock.find("name = \"Alpha\"").unwrap();
    let app = lock.find("name = \"App\"").unwrap();
    assert!(
        alpha < app,
        "dependencies are written before dependents:\n{lock}"
    );

    // The lockfile is current, so a second plan reads it and writes nothing.
    let again = plan_for(&tree, "src/Main.mmt", &[tree.path("env"), tree.path("src")]);
    assert_eq!(again, plan);
    assert_eq!(tree.read("marmot.lock"), lock);
}

#[test]
fn editing_the_manifest_resolves_again() {
    let tree = TempTree::new(&[
        ("project.marmot", &project(&[("Lib", "^1.0.0")])),
        ("src/Main.mmt", "module Main\n"),
        (
            "registry/Lib1/package.marmot",
            &package("Lib", "1.0.0", &[]),
        ),
        (
            "registry/Lib2/package.marmot",
            &package("Lib", "2.1.0", &[]),
        ),
    ]);
    let first = plan_for(&tree, "src/Main.mmt", &[]);
    assert!(
        first
            .search_paths
            .contains(&shown(&tree.path("packages/Lib-1.0.0")))
    );

    tree.write("project.marmot", &project(&[("Lib", "^2.0.0")]));
    let second = plan_for(&tree, "src/Main.mmt", &[]);
    assert!(
        second
            .search_paths
            .contains(&shown(&tree.path("packages/Lib-2.1.0")))
    );
    assert!(tree.read("marmot.lock").contains("version = \"2.1.0\""));
}

#[test]
fn a_changed_installed_copy_is_replaced_from_the_index() {
    let tree = TempTree::new(&[
        ("project.marmot", &project(&[("Lib", "^1.0.0")])),
        ("src/Main.mmt", "module Main\n"),
        ("registry/Lib/package.marmot", &package("Lib", "1.0.0", &[])),
        ("registry/Lib/Lib.mmt", "module Lib\n"),
    ]);
    plan_for(&tree, "src/Main.mmt", &[]);

    // Someone edits the installed copy's version: the lock no longer holds, and
    // resolving again restores the copy from the registry.
    tree.write(
        "packages/Lib-1.0.0/package.marmot",
        &package("Lib", "3.0.0", &[]),
    );
    plan_for(&tree, "src/Main.mmt", &[]);
    assert_eq!(
        tree.read("packages/Lib-1.0.0/package.marmot"),
        package("Lib", "1.0.0", &[])
    );
}

#[test]
fn a_changed_package_source_is_a_warning_not_a_resolution() {
    let tree = TempTree::new(&[
        ("project.marmot", &project(&[("Lib", "^1.0.0")])),
        ("src/Main.mmt", "module Main\n"),
        ("registry/Lib/package.marmot", &package("Lib", "1.0.0", &[])),
        ("registry/Lib/Lib.mmt", "module Lib\n"),
    ]);
    plan_for(&tree, "src/Main.mmt", &[]);
    let lock = tree.read("marmot.lock");

    tree.write("packages/Lib-1.0.0/Lib.mmt", "module Lib\n// edited\n");
    let (_, warnings) = make_plan(&tree.path("src/Main.mmt"), &[], &compiler()).unwrap();
    assert_eq!(
        warnings,
        vec!["Package 'Lib' has changed since the lockfile was generated.".to_string()]
    );
    assert_eq!(tree.read("marmot.lock"), lock);
}

#[test]
fn a_package_manifest_is_a_workspace_rooted_at_itself() {
    let tree = TempTree::new(&[
        (
            "Pkg/package.marmot",
            &(package("Pkg", "1.0.0", &[]) + "\n[ffi]\nenabled = true\nlibrary_name = \"pkg\"\n"),
        ),
        ("Pkg/Pkg.mmt", "module Pkg\n"),
    ]);

    let plan = plan_for(&tree, "Pkg/Pkg.mmt", &[]);

    assert_eq!(plan.search_paths, vec![shown(&tree.path("Pkg"))]);
    assert_eq!(plan.native_libraries.len(), 1);
    assert_eq!(plan.native_libraries[0].name, "pkg");
    assert!(tree.path("Pkg/marmot.lock").exists());
}

#[test]
fn native_libraries_come_from_installed_packages() {
    let tree = TempTree::new(&[
        ("project.marmot", &project(&[("Native", "^1.0.0")])),
        ("src/Main.mmt", "module Main\n"),
        (
            "registry/Native/package.marmot",
            &(package("Native", "1.0.0", &[])
                + "\n[ffi]\nenabled = true\nlibrary_name = \"native\"\nthread_safe = true\n\n[prebuilt.windows_x64]\npath = \"bin/native.dll\"\nchecksum = \"sha256:ab\"\n"),
        ),
    ]);

    let plan = plan_for(&tree, "src/Main.mmt", &[]);

    assert_eq!(plan.native_libraries.len(), 1);
    let native = &plan.native_libraries[0];
    assert_eq!(native.name, "native");
    assert!(native.thread_safe);
    if cfg!(windows) {
        assert_eq!(
            native.path,
            shown(&tree.path("packages/Native-1.0.0/bin/native.dll"))
        );
        assert_eq!(native.checksum.as_deref(), Some("sha256:ab"));
    }
}

#[test]
fn a_package_without_ffi_or_with_another_abi_is_not_native() {
    let tree = TempTree::new(&[
        ("app/Main.mmt", "module Main\n"),
        ("plain/package.marmot", &package("Plain", "1.0.0", &[])),
        (
            "old/package.marmot",
            &(package("Old", "1.0.0", &[])
                + "\n[ffi]\nenabled = true\nlibrary_name = \"old\"\nabi_version = 2\n"),
        ),
    ]);

    let plan = plan_for(
        &tree,
        "app/Main.mmt",
        &[tree.path("plain"), tree.path("old")],
    );

    assert_eq!(plan.search_paths.len(), 2);
    assert!(plan.native_libraries.is_empty());
}

#[test]
fn a_package_that_still_lists_ffi_functions_is_named_in_a_warning() {
    let tree = TempTree::new(&[
        ("app/Main.mmt", "module Main\n"),
        (
            "legacy/package.marmot",
            &(package("Legacy", "1.0.0", &[])
                + "\n[ffi]\nenabled = true\nlibrary_name = \"legacy\"\n\n[ffi.functions]\n\"F\" = \"f\"\n"),
        ),
    ]);

    let (plan, warnings) = make_plan(
        &tree.path("app/Main.mmt"),
        &[tree.path("legacy")],
        &compiler(),
    )
    .unwrap();

    assert!(plan.native_libraries.is_empty());
    assert_eq!(warnings.len(), 1, "{warnings:?}");
    assert!(warnings[0].contains("[ffi.functions]"), "{}", warnings[0]);
    assert!(warnings[0].contains("from \"legacy\""), "{}", warnings[0]);
}

#[test]
fn project_manifest_without_a_project_table_is_an_error() {
    let tree = TempTree::new(&[
        ("project.marmot", "[dependencies]\n"),
        ("src/Main.mmt", "module Main\n"),
    ]);
    let error = make_plan(&tree.path("src/Main.mmt"), &[], &compiler()).unwrap_err();
    assert!(error.contains("missing [project] table"), "{error}");
}

#[test]
fn the_plan_serialises_as_the_compiler_expects() {
    let plan = Plan {
        version: 1,
        entry: Some("E".into()),
        search_paths: vec!["S".into()],
        native_libraries: vec![PlanNativeLibrary {
            name: "n".into(),
            path: "P".into(),
            thread_safe: false,
            checksum: None,
        }],
    };
    let json: serde_json::Value = serde_json::from_str(&plan.to_json()).unwrap();
    assert_eq!(
        json,
        serde_json::json!({
            "version": 1,
            "entry": "E",
            "search_paths": ["S"],
            "native_libraries": [{ "name": "n", "thread_safe": false }]
        })
    );
}
